### ISSUE TITLE
老哥，该方法用sigmoid的bce loss做多标签分类不收敛是什么原因呢

### ISSUE THREAD

**Issue by tankland** [xueyouluo/Biaffine-BERT-NER#2]

**Comment by xueyouluo** [comment]
我还没试过多标签分类，你的一个span还能属于多个类别吗？  我能想到的一个是试试调参；另外看看能不能用Pipeline的方法，先用这个模型找到要抽的span，然后再用一个模型去判断span到底属于什么类别。

**Comment by lishuanzhu** [comment]
感谢作者，参照着用tf2实现的，改了好多地方。
1. 前面是bert的encoder_output最后两层, Bert直接加入训练
2. 接bilstm
3. 两个FFNN分别预测起始位置
4. 扔给Biaffine
5. 全连接+sigmoid

数据generator比较麻烦:
1. token和字符mapping之后，因为OOV问题, mapping会有缺失
2. 对缺失mapping专门补齐
3. 生成一个max_seq_len, max_seq_len, num_class+1的矩阵, 对对应位置填充label
4. 这个矩阵超级稀疏，也特别大，训练是个问题。用了一些奇技淫巧往loss传token长度(tensorflow太不灵活了)

loss:
就是binary_crossentropy, 用前面传过来的token按长度截断计算


大体思路如上，代码没法开源，但感谢作者，希望也能帮到楼主
